Namespace(batchSize=16, cuda=True, dataset='datasets/', lr=0.0001, momentum=0.9, nEpochs=5000, resume='', start_epoch=1, step=1000, test_path='dataset/test/', threads=16, validate_path='datasets/validate/', weight_decay=0)
===> Loading datasets
===> Building model
n_pyramids: 1 n_pyramid_cells: (3, 2, 1, 1, 1, 1)
===> Setting GPU
===> Setting Optimizer
===> Training
Epoch=1, lr=0.0001
===> Epoch[1](1/11): Loss: 0.3700003028
===> Epoch[1](2/11): Loss: 0.3738734126
===> Epoch[1](3/11): Loss: 0.3794515133
===> Epoch[1](4/11): Loss: 0.4448431730
===> Epoch[1](5/11): Loss: 0.3415575027
===> Epoch[1](6/11): Loss: 0.3219466805
===> Epoch[1](7/11): Loss: 0.3857696652
===> Epoch[1](8/11): Loss: 0.3948265016
===> Epoch[1](9/11): Loss: 0.3521016538
===> Epoch[1](10/11): Loss: 0.2927230597
===> Epoch[1](11/11): Loss: 0.2635369301
|||||||||||||||||||||min_epoch_loss is 0.3564209450|||||||||||||||||||||
----Start Validate----
Traceback (most recent call last):
  File "train_psnr_indication.py", line 331, in <module>
    main()
  File "train_psnr_indication.py", line 160, in main
    validate(model, optimizer, epoch)
  File "train_psnr_indication.py", line 296, in validate
    for iteration, batch in enumerate(validate_data_loader, 1):
  File "/home/pxk/anaconda3/envs/cxy/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 517, in __next__
    data = self._next_data()
  File "/home/pxk/anaconda3/envs/cxy/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 557, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "/home/pxk/anaconda3/envs/cxy/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/pxk/anaconda3/envs/cxy/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/pxk/CBREN/dataset.py", line 159, in __getitem__
    folder_index = random.randint(0, (len(self.folder_list) - 1))
AttributeError: 'ValidateDataset' object has no attribute 'folder_list'