Namespace(batchSize=16, cuda=True, dataset='datasets/', lr=0.0001, momentum=0.9, nEpochs=2000, resume='', start_epoch=1, step=1000, test_path='dataset/test/', threads=16, validate_path='datasets/validate/', weight_decay=0)
===> Loading datasets
Traceback (most recent call last):
  File "train_psnr_indication.py", line 313, in <module>
    main()
  File "train_psnr_indication.py", line 124, in main
    train_set = get_training_set()
  File "/home/pxk/CBREN/dataset.py", line 21, in get_training_set
    return TrainDatasetMultiFrame(dir=root_path)
TypeError: __init__() got an unexpected keyword argument 'dir'